<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Infrastructure &amp; Operations – GLITCH</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-metodologia-y-disciplina.html" rel="next">
<link href="./02-cerebro2-timeline.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-0626ff4d7a71b55c8707dcae1d04a9b6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5286facc3d161db56da1629c96e68e53.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">GLITCH</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <a href="https://github.com/erictvillarreal/GLITCH" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-infraestructura-operaciones.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Infrastructure &amp; Operations</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Executive Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-cerebro1-timeline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Cerebro 1 — Timeline</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-cerebro2-timeline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Cerebro 2 — Timeline</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-infraestructura-operaciones.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Infrastructure &amp; Operations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-metodologia-y-disciplina.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Methodology &amp; Discipline</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-glosario.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Glossary</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-combo2d-crash-chain-2.5-weeks-five-distinct-root-causes" id="toc-the-combo2d-crash-chain-2.5-weeks-five-distinct-root-causes" class="nav-link active" data-scroll-target="#the-combo2d-crash-chain-2.5-weeks-five-distinct-root-causes"><span class="header-section-number">4.1</span> The COMBO2D crash chain — 2.5 weeks, five distinct root causes</a></li>
  <li><a href="#deployment-configuration-inconsistency-four-files-three-different-start-commands" id="toc-deployment-configuration-inconsistency-four-files-three-different-start-commands" class="nav-link" data-scroll-target="#deployment-configuration-inconsistency-four-files-three-different-start-commands"><span class="header-section-number">4.2</span> Deployment configuration inconsistency — four files, three different start commands</a></li>
  <li><a href="#ephemeral-filesystem-a-data-quality-problem-a-total-data-loss-problem" id="toc-ephemeral-filesystem-a-data-quality-problem-a-total-data-loss-problem" class="nav-link" data-scroll-target="#ephemeral-filesystem-a-data-quality-problem-a-total-data-loss-problem"><span class="header-section-number">4.3</span> Ephemeral filesystem — <del>a data-quality problem</del> a total data-loss problem</a></li>
  <li><a href="#unified-startup-environment-check" id="toc-unified-startup-environment-check" class="nav-link" data-scroll-target="#unified-startup-environment-check"><span class="header-section-number">4.4</span> Unified startup environment check</a></li>
  <li><a href="#yahoo-finance-mesf-opening-window-delay" id="toc-yahoo-finance-mesf-opening-window-delay" class="nav-link" data-scroll-target="#yahoo-finance-mesf-opening-window-delay"><span class="header-section-number">4.5</span> Yahoo Finance MES=F opening-window delay</a></li>
  <li><a href="#massive-migration-api-pagination-quirk-found-twice" id="toc-massive-migration-api-pagination-quirk-found-twice" class="nav-link" data-scroll-target="#massive-migration-api-pagination-quirk-found-twice"><span class="header-section-number">4.6</span> Massive migration — API pagination quirk found twice</a></li>
  <li><a href="#mgcs-real-trading-liquidity-window-was-miscalibrated-for-the-whole-dataset-not-just-live-entry" id="toc-mgcs-real-trading-liquidity-window-was-miscalibrated-for-the-whole-dataset-not-just-live-entry" class="nav-link" data-scroll-target="#mgcs-real-trading-liquidity-window-was-miscalibrated-for-the-whole-dataset-not-just-live-entry"><span class="header-section-number">4.7</span> MGC’s real trading-liquidity window was miscalibrated — for the whole dataset, not just live entry</a></li>
  <li><a href="#same-day-finding-utc-mislabeled-as-ct-logger-07-september-2026" id="toc-same-day-finding-utc-mislabeled-as-ct-logger-07-september-2026" class="nav-link" data-scroll-target="#same-day-finding-utc-mislabeled-as-ct-logger-07-september-2026"><span class="header-section-number">4.8</span> Same-day finding: UTC-mislabeled-as-CT logger (07 September 2026)</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/erictvillarreal/GLITCH/edit/main/03-infraestructura-operaciones.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/erictvillarreal/GLITCH/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Infrastructure &amp; Operations</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This chapter is a chronicle of operational incidents — deployment, persistence, data-source reliability — as distinct from the statistical findings in <a href="./01-cerebro1-timeline.html">Cerebro 1</a> and <a href="./02-cerebro2-timeline.html">Cerebro 2</a>. Nothing here is evidence of trading edge; a service running cleanly is a hygiene fact, not a validation result.</p>
</div>
</div>
<section id="the-combo2d-crash-chain-2.5-weeks-five-distinct-root-causes" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="the-combo2d-crash-chain-2.5-weeks-five-distinct-root-causes"><span class="header-section-number">4.1</span> The COMBO2D crash chain — 2.5 weeks, five distinct root causes</h2>
<p>Between 14 August and 1 September 2026, the <code>combo2d_scheduler.py</code> service failed to execute successfully <strong>a single time</strong> — 12 consecutive failed runs, each crashing in 3–4 seconds during import, before ever reaching <code>run()</code>. Reconstructed in full from <code>git log</code>/<code>git show</code> and Railway’s own Cron Run history:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Date (UTC)</th>
<th>Commit</th>
<th>What happened</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Jul 8 – Aug 13</td>
<td>—</td>
<td>The service was actually running <code>glitch_scheduler.py</code>, a separate, earlier script — confirmed via <a href="https://github.com/erictvillarreal/GLITCH/commit/e0b1ea3"><code>git show e0b1ea3:Procfile</code></a>. The clean 15–19 minute runs from this period have nothing to do with combo2d.</td>
</tr>
<tr class="even">
<td>Aug 13, 21:31</td>
<td><a href="https://github.com/erictvillarreal/GLITCH/commit/1a3b714"><code>1a3b714</code></a></td>
<td><code>combo2d_scheduler.py</code> created; Procfile pointed at it for the first time</td>
</tr>
<tr class="odd">
<td>Aug 13, 23:58</td>
<td><a href="https://github.com/erictvillarreal/GLITCH/commit/cb070a5"><code>cb070a5</code></a></td>
<td>Switched to <code>massive</code>/<code>RESTClient</code> for data — but <code>massive</code> was never added to the root <code>requirements.txt</code></td>
</tr>
<tr class="even">
<td>Aug 17, 14:45</td>
<td><a href="https://github.com/erictvillarreal/GLITCH/commit/321c747"><code>321c747</code></a></td>
<td>“fix: add massive to scheduler requirements” — added <code>massive</code> to <code>glitch/scheduler/requirements.txt</code>, the <strong>wrong file</strong>: this service builds via Railpack, which reads the root <code>requirements.txt</code>, not the scheduler subdirectory’s copy. The fix had zero real effect.</td>
</tr>
<tr class="odd">
<td>Aug 17 – Aug 26</td>
<td>—</td>
<td><strong>9 days with no commits</strong> — the service failing silently, unnoticed</td>
</tr>
<tr class="even">
<td>Aug 26–27</td>
<td><a href="https://github.com/erictvillarreal/GLITCH/commit/99497ec"><code>99497ec</code></a></td>
<td>Security hardening merged (removed hardcoded Massive/Telegram fallbacks) — but <code>massive</code> was still missing from the correct file, so execution still died <em>before</em> reaching the new Telegram check</td>
</tr>
<tr class="odd">
<td>Aug 28</td>
<td><a href="https://github.com/erictvillarreal/GLITCH/commit/44f07cf"><code>44f07cf</code></a></td>
<td>Fixed the correct file (root <code>requirements.txt</code>) — first time since Aug 13 the <code>massive</code> import actually resolves</td>
</tr>
<tr class="even">
<td>Aug 31</td>
<td>—</td>
<td>With the import resolved, execution reached the <em>next</em> unmet requirement — the Telegram token — surfacing a new-looking error that was really the second domino in the same chain</td>
</tr>
</tbody>
</table>
<p><strong>Explicit conclusion:</strong> this session’s own security hardening (removing hardcoded fallbacks) was not the original cause — it stacked a second requirement (Telegram env vars) behind a pre-existing bug from 17 August that touched the wrong file. Any COMBO2D “Win Rate” or “PnL Total” Telegram report between 14 August and the fix must be treated as <strong>nonexistent, not as contaminated data</strong> — the service simply never ran.</p>
<p><strong>Related, separate bug found earlier in the same investigation</strong> — an intermediate commit (<a href="https://github.com/erictvillarreal/GLITCH/commit/4eed7ca"><code>4eed7ca</code></a>) found that the Nixpacks build phase (a different build path than the Railpack one actually in use) installs from <code>glitch/scheduler/requirements.txt</code>, not the root file — the opposite convention from Railpack. Two build systems reading two different requirements files was the structural reason the same class of bug (“added the dependency, to the wrong file”) could recur.</p>
</section>
<section id="deployment-configuration-inconsistency-four-files-three-different-start-commands" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="deployment-configuration-inconsistency-four-files-three-different-start-commands"><span class="header-section-number">4.2</span> Deployment configuration inconsistency — four files, three different start commands</h2>
<p>While preparing to add a second Railway service (for the Cerebro 1 geometry candidate), an audit found four config files disagreeing on the start command:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>File</th>
<th>Start command</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>nixpacks.toml</code> (root)</td>
<td><code>python glitch/scheduler/glitch_scheduler.py</code></td>
</tr>
<tr class="even">
<td><code>Procfile</code> (root)</td>
<td><code>python glitch/scheduler/combo2d_scheduler.py</code></td>
</tr>
<tr class="odd">
<td><code>glitch/Procfile</code></td>
<td><code>python scheduler/glitch_scheduler.py</code></td>
</tr>
<tr class="even">
<td><code>glitch/railway.json</code></td>
<td><code>python scheduler/glitch_scheduler.py</code></td>
</tr>
</tbody>
</table>
<p>The initial hypothesis — that Railway’s dashboard had a manual Start Command override ignoring these files — was checked directly and <strong>ruled out</strong>: the combo2d service’s Start Command field is empty, meaning Railway genuinely reads one of the four files, yet 3 of 4 point to the old <code>glitch_scheduler.py</code> while <code>combo2d_scheduler.py</code> is confirmed to be what’s actually running. This discrepancy was never fully resolved; it was treated as a live risk (never edit <code>nixpacks.toml</code> or <code>glitch/Procfile</code> without first confirming Railway’s configured Root Directory) rather than guessed past. See <a href="https://github.com/erictvillarreal/GLITCH/blob/99497ec/glitch/GLITCH_RESEARCH_LOG.md"><code>GLITCH_RESEARCH_LOG.md</code>, “Despliegue a Railway”</a>.</p>
</section>
<section id="ephemeral-filesystem-a-data-quality-problem-a-total-data-loss-problem" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="ephemeral-filesystem-a-data-quality-problem-a-total-data-loss-problem"><span class="header-section-number">4.3</span> Ephemeral filesystem — <del>a data-quality problem</del> a total data-loss problem</h2>
<p>Confirmed directly on Railway’s dashboard: Cron Schedule-type services (GEOMETRY, and by the same service type, COMBO2D) have no Volumes option — <strong>the filesystem resets between every cron execution.</strong> Both schedulers stored their trade history in a local JSON file, so every run started from a blank slate. Every “Día X de paper” or “pass_rate acumulado” message ever sent to Telegram before this fix reflected, at most, a single day’s cycle — never a real accumulation, even though the message read like a running total. Once the COMBO2D crash chain above was reconstructed, this was revealed to be moot for that period specifically (there was no successful run to lose state from until 28 August), but it remained a live, general risk for GEOMETRY.</p>
<p><strong>Fix:</strong> <a href="https://github.com/erictvillarreal/GLITCH/commit/6a548a3"><code>6a548a3</code></a> — <code>execution/gist_store.py</code>, a private GitHub Gist accessed via the REST API, as the single persistence backend for both schedulers, replacing local-file I/O behind the same <code>load_log()</code>/<code>save_log()</code> interface. Two alternatives were evaluated and rejected first: Railway Volumes (confirmed unavailable for this service type) and reading the bot’s own message history back via Telegram’s <code>getUpdates</code> (confirmed technically impossible — the Bot API never returns a bot’s own sent messages to itself). Failure philosophy is deliberately asymmetric: missing configuration (<code>GITHUB_GIST_TOKEN</code>, <code>GIST_ID</code>) raises immediately rather than silently starting a scheduler that thinks it’s on day one; a transient network failure during a well-configured run logs but does not crash the scheduler, since the day’s trade has already executed and been notified by that point. 10 dedicated tests (<code>tests/test_gist_store.py</code>, no real network — mocked <code>requests.get</code>/<code>requests.patch</code>) plus integration coverage in both parity test files; full suite 110/110.</p>
</section>
<section id="unified-startup-environment-check" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="unified-startup-environment-check"><span class="header-section-number">4.4</span> Unified startup environment check</h2>
<p>The COMBO2D crash chain’s real underlying pattern — five separate root causes discovered one crash at a time, each hiding the next — prompted a structural fix rather than another one-off patch: <a href="https://github.com/erictvillarreal/GLITCH/commit/a24400f"><code>a24400f</code></a> added <code>execution/env_check.py</code>, called as the very first line of both schedulers, before any of the three modules (<code>telegram_bot</code>, <code>contracts</code>, <code>gist_store</code>) that each used to validate their own required variables independently, one crash-and-fix cycle apart. It checks all five required variables (<code>MASSIVE_API_KEY</code>/<code>POLYGON_API_KEY</code>, <code>TELEGRAM_BOT_TOKEN</code>, <code>TELEGRAM_CHAT_ID</code>, <code>GITHUB_GIST_TOKEN</code>, <code>GIST_ID</code>) at once and sends a single Telegram message listing every missing one, rather than surfacing them serially across separate days. Verified with 6 unit tests plus a real build-environment smoke test: importing each scheduler under <code>env -i</code> with exactly the 7 variables Railway has configured, confirming a clean import end-to-end, not just a passing check. A manual “Run now” trigger on 2 September 2026 gave the first real, clean end-to-end log for COMBO2D since the incident began — full suite 118/118 passing at that point.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Fixing the crash chain is infrastructure hygiene, not evidence of trading edge. COMBO2D is technically healthy today (it runs start to finish without error) — but it remains the <code>combo_2d</code> mean-reversion candidate already discarded on statistical grounds (fresh reproduction gave p≈0.44–0.45; see <a href="./01-cerebro1-timeline.html">Cerebro 1 Timeline</a> and <a href="./04-metodologia-y-disciplina.html">Methodology &amp; Discipline</a>). A clean log is not a signal.</p>
</div>
</div>
</section>
<section id="yahoo-finance-mesf-opening-window-delay" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="yahoo-finance-mesf-opening-window-delay"><span class="header-section-number">4.5</span> Yahoo Finance MES=F opening-window delay</h2>
<p>An earlier, separate incident chain (predating the Massive migration) affected the ORB-based scheduler’s live entry: Yahoo Finance’s free MES=F feed frequently had no data yet at the scheduled 9:30 CT entry check, producing zero-range opening bars. Fixed iteratively across several commits — skip the trading day if the scheduler starts after the ORB window closes (<a href="https://github.com/erictvillarreal/GLITCH/commit/e038911"><code>e038911</code></a>), retry on a zero-range ORB instead of assuming the market itself was flat (<a href="https://github.com/erictvillarreal/GLITCH/commit/53b03a6"><code>53b03a6</code></a>), correct the retry’s sleep target (<a href="https://github.com/erictvillarreal/GLITCH/commit/ada0bc0"><code>ada0bc0</code></a>), log actual bar timestamps to confirm the fetch window truly aligned with 9:30–9:34 (<a href="https://github.com/erictvillarreal/GLITCH/commit/1a8a76c"><code>1a8a76c</code></a>), widen the entry-fetch window with per-attempt diagnostics (<a href="https://github.com/erictvillarreal/GLITCH/commit/7e0d53d"><code>7e0d53d</code></a>) — and finally diagnosed with a dedicated standalone real-time probe deployed as its own one-shot Railway service (<a href="https://github.com/erictvillarreal/GLITCH/commit/97c522a"><code>97c522a</code></a>, <a href="https://github.com/erictvillarreal/GLITCH/commit/73a4ab9"><code>73a4ab9</code></a>) rather than guessed at from inside the live scheduler. This data-reliability problem, among others, motivated the later migration to Massive as the primary market-data source.</p>
</section>
<section id="massive-migration-api-pagination-quirk-found-twice" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="massive-migration-api-pagination-quirk-found-twice"><span class="header-section-number">4.6</span> Massive migration — API pagination quirk found twice</h2>
<p>Massive’s REST API has a specific, non-obvious failure mode: requesting a date range with <code>sort=window_start.asc</code> and taking the last row of the response does <strong>not</strong> reliably return the most recent bar — confirmed independently on two different endpoints, seven days apart:</p>
<p><strong>First occurrence — <code>/futures/v1/contracts</code></strong> (during the original Massive migration): a point-in-time <code>date=</code> query works reliably; a wide date range with ascending sort does not.</p>
<p><strong>Second occurrence — <code>/futures/v1/aggs/{ticker}</code>, MGC delay probe (07 September 2026):</strong> a first attempt to measure Massive’s real-time data delay for MGC (<code>scripts/probe_massive_mgc_delay.py</code>) returned an impossible result — <strong>~319,174 minutes (over 7 months) of “delay.”</strong> Rather than re-run the measurement blindly, three query variants were tested side by side against the same endpoint (<code>scripts/diagnose_massive_aggs_query.py</code>, <a href="https://github.com/erictvillarreal/GLITCH/commit/e56322e">commit <code>e56322e</code></a>):</p>
<ul>
<li><strong>A)</strong> Date-only range bounds + <code>sort=window_start.asc</code> + high <code>limit</code>, taking the last result (the pattern that worked for full historical downloads in <code>fetch_mes_2y.py</code>)</li>
<li><strong>B)</strong> Same pattern with full datetime + timezone offset instead of a bare date</li>
<li><strong>C)</strong> No date range at all — <code>sort=window_start.desc</code> + <code>limit=1</code>, asking directly for “the most recent bar you have”</li>
</ul>
<p><strong>Only C works.</strong> A and B both fail identically regardless of date-format — confirming this is an API pagination/ordering issue specific to <code>sort=asc</code> + range + take-last, the same failure class already seen on <code>/futures/v1/contracts</code>, not a one-off. <strong>Rule adopted for any future “give me the latest” query against Massive: <code>sort=desc</code> + small <code>limit</code>, never a date range with <code>sort=asc</code> and take-the-last-element.</strong> Fixed in <a href="https://github.com/erictvillarreal/GLITCH/commit/2a1c910">commit <code>2a1c910</code></a>.</p>
<p>A second, independent measurement artifact was caught in the same fix: the corrected probe’s first real run measured ~1.8 days of “delay” — but it ran on a <strong>Saturday</strong>, so the number was elapsed time since Friday’s market close (gold trades Fri 16:00 CT–Sun 17:00 CT), not real API latency. A <code>_weekday_warning()</code> guard was added so the probe flags itself when run outside active weekday market hours; the real delay measurement remains pending a weekday run.</p>
</section>
<section id="mgcs-real-trading-liquidity-window-was-miscalibrated-for-the-whole-dataset-not-just-live-entry" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="mgcs-real-trading-liquidity-window-was-miscalibrated-for-the-whole-dataset-not-just-live-entry"><span class="header-section-number">4.7</span> MGC’s real trading-liquidity window was miscalibrated — for the whole dataset, not just live entry</h2>
<p>While building the third scheduler’s entry-window logic (Cerebro 2’s checklist item explicitly warning not to assume equity-index RTH conventions transfer to other products), a deeper problem surfaced: the <em>entire</em> <code>mgc_5min_2y.parquet</code> dataset already used to validate this candidate’s win rate had the same miscalibration. <code>fetch_mes_2y.py</code> (reused to fetch MGC) filtered to “8:30–15:00 CT, standard for index products” — a filter written for equity index and never revisited for gold.</p>
<p>Checked against two independent external sources — CME/COMEX’s legacy pit session (7:20–12:30 CT) and the commonly cited London-NY overlap window for gold’s highest real liquidity (7:00–11:00 CT) — both place gold’s real active window <strong>1–1.5 hours earlier</strong> than 8:30 CT. Internal evidence corroborated this independently: in the existing dataset, the very first captured bar (8:30 CT) was already the day’s volume peak (29.1% of the day’s total volume in that first hour alone), decaying monotonically afterward — a slope that, extrapolated backward, suggests the untouched 7:00–8:30 CT window was probably <em>more</em> active than anything already captured, not less. <a href="https://github.com/erictvillarreal/GLITCH/commit/47350ba">Commit <code>47350ba</code></a>.</p>
<p>A corrected-window fetch script (<code>scripts/fetch_mgc_correct_window.py</code>) was prepared but not run locally (blocked on <code>MASSIVE_API_KEY</code>, deliberately not passed into this session per the project’s key-handling rule) — the user ran it from their own environment. Comparison, once the corrected dataset (49,395 bars, 7:00–15:00 CT, +22.9% more data) came back:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Old window (8:30–15:00 CT)</th>
<th><strong>Corrected window (7:00–15:00 CT)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Conditional WR (all)</td>
<td>49.97%</td>
<td><strong>50.20%</strong></td>
</tr>
<tr class="even">
<td>WR long / short</td>
<td>52.78% / 47.16% (5.62pp gap)</td>
<td><strong>50.47% / 49.93%</strong> (0.54pp gap)</td>
</tr>
<tr class="odd">
<td>Combine pass rate (alternating)</td>
<td>47.0%</td>
<td><strong>47.5%</strong></td>
</tr>
</tbody>
</table>
<p>The corrected window is now the reference dataset for this candidate: it captured meaningfully more data, pushed the win rate even closer to the 50% theoretical assumption, and <strong>nearly eliminated the long/short asymmetry</strong> — consistent with the idea that part of that asymmetry was an artifact of excluding the window where buy/sell order flow is most balanced, not a genuine market bias. The Combine pass rate barely moved (47.0% → 47.5%), so the central conclusion that this candidate is weak for the Combine phase (vs.&nbsp;G2’s 81.4%) is unaffected. <a href="https://github.com/erictvillarreal/GLITCH/commit/0ef0c15">Commit <code>0ef0c15</code></a> confirms this was a real improvement, not just a formality. A stale-hardcoded-aggregate bug caught in the comparison script itself along the way (<a href="https://github.com/erictvillarreal/GLITCH/commit/3f0bd07">commit <code>3f0bd07</code></a>) is documented in <a href="./02-cerebro2-timeline.html">Cerebro 2 Timeline</a>.</p>
<p>This finding is scoped to MGC specifically — <code>mgc_5min_2y.parquet</code> (old window) remains valid and untouched for the original, narrower-barrier <code>CANDIDATES["MGC"]</code> geometry used in Cerebro 1’s product grid, which is not affected by the same time-exit dynamics.</p>
</section>
<section id="same-day-finding-utc-mislabeled-as-ct-logger-07-september-2026" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="same-day-finding-utc-mislabeled-as-ct-logger-07-september-2026"><span class="header-section-number">4.8</span> Same-day finding: UTC-mislabeled-as-CT logger (07 September 2026)</h2>
<p>Found while writing this report, not during the original edge search: all 3 production schedulers (<code>geometry_scheduler.py</code>, <code>combo2d_scheduler.py</code>, <code>glitch_scheduler.py</code>) used <code>logging.basicConfig(format="%(asctime)s CT ...")</code> — a literal <code>"CT"</code> string in the format, with <code>%(asctime)s</code> defaulting to <code>time.localtime()</code>. This showed the correct time <strong>only because</strong> Railway happens to have <code>TZ=America/Chicago</code> set; had that variable ever been absent (the typical default for a bare Docker container is UTC), every log line would have shown UTC time mislabeled as CT, with no visible error. Confirmed empirically (forcing <code>TZ=UTC</code> vs.&nbsp;<code>TZ=America/Chicago</code> before applying any fix) rather than assumed already-fixed from a passing description.</p>
<p><strong>Fix:</strong> a new single-source-of-truth module, <a href="https://github.com/erictvillarreal/GLITCH/blob/484187c/glitch/execution/ct_logging.py"><code>execution/ct_logging.py</code></a>, with a <code>CTFormatter</code> whose <code>converter</code> explicitly resolves to <code>zoneinfo.ZoneInfo("America/Chicago")</code>, independent of the process’s <code>TZ</code> or <code>time.localtime()</code>. A permanent regression test (<code>tests/test_ct_logging.py</code>) forces <code>TZ=UTC</code> at the process level and confirms logged timestamps still reflect real Chicago time, including a summer case to confirm DST is honored rather than a fixed offset. Applied in <a href="https://github.com/erictvillarreal/GLITCH/commit/484187c">commit <code>484187c</code></a> (<code>main</code>: <code>geometry_scheduler.py</code>, <code>combo2d_scheduler.py</code>, <code>glitch_scheduler.py</code>) and <a href="https://github.com/erictvillarreal/GLITCH/commit/0be4b01">commit <code>0be4b01</code></a> (<code>cerebro2-dev</code>: <code>geometry_mgc_scheduler.py</code>).</p>
<p><strong>Side finding, unrelated to the fix itself:</strong> smoke-testing <code>glitch_scheduler.py</code> revealed it <strong>cannot be imported at all</strong> — <code>from scheduler.telegram_bot import notify_signal, notify_exit, ...</code> fails, because those functions no longer exist in <code>telegram_bot.py</code> (replaced at some point by the Brain1/Brain2 template rework; current exports are <code>send</code>, <code>notify_brain1_open/close/no_signal</code>, <code>notify_brain2_open/close/no_signal</code>, and related functions). Confirmed via <code>git diff</code> to be pre-existing, unrelated to this logging fix. This is strong circumstantial evidence that <code>glitch_scheduler.py</code> is orphaned code — if it were the service actually running behind the root <code>Procfile</code>’s <code>worker:</code> line, it would be visibly crash-looping since the Brain1/Brain2 rework, which is unlikely to have gone unnoticed for this long. <strong>Not fixed</strong> — out of scope for this same-day finding; deployment dashboards for GEOMETRY, GEOMETRY-MGC, and GLITCH all confirmed “Deployment successful” as of this writing (06 September 2026, a Sunday with no active cron), but which specific file the Railway service named “GLITCH” actually executes was not conclusively confirmed in this session.</p>
<p><strong>Correction to the bug list for this report:</strong> of the 4 items originally slated to appear as “bugs found during the edge search,” only 2 have a confirmed root cause and fix from that original search: the <code>triple_barrier.py</code> ambiguous-bar bug and the ZC tick-size unit mismatch (both in <a href="./01-cerebro1-timeline.html">Cerebro 1 Timeline</a>). “MES/MNQ tick value confusion” is dropped — no evidence it was ever a real bug. The UTC-as-CT logger bug documented here is a same-day finding from writing this report, not a historical artifact of the original edge search — the two timelines are kept separate deliberately, not conflated.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-cerebro2-timeline.html" class="pagination-link" aria-label="Cerebro 2 — Timeline">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Cerebro 2 — Timeline</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-metodologia-y-disciplina.html" class="pagination-link" aria-label="Methodology &amp; Discipline">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Methodology &amp; Discipline</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Infrastructure &amp; Operations</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>This chapter is a chronicle of operational incidents — deployment, persistence, data-source reliability — as distinct from the statistical findings in <span class="co">[</span><span class="ot">Cerebro 1</span><span class="co">](01-cerebro1-timeline.qmd)</span> and <span class="co">[</span><span class="ot">Cerebro 2</span><span class="co">](02-cerebro2-timeline.qmd)</span>. Nothing here is evidence of trading edge; a service running cleanly is a hygiene fact, not a validation result.</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## The COMBO2D crash chain — 2.5 weeks, five distinct root causes</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>Between 14 August and 1 September 2026, the <span class="in">`combo2d_scheduler.py`</span> service failed to execute successfully **a single time** — 12 consecutive failed runs, each crashing in 3–4 seconds during import, before ever reaching <span class="in">`run()`</span>. Reconstructed in full from <span class="in">`git log`</span>/<span class="in">`git show`</span> and Railway's own Cron Run history:</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>| Date (UTC) | Commit | What happened |</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>| Jul 8 – Aug 13 | — | The service was actually running <span class="in">`glitch_scheduler.py`</span>, a separate, earlier script — confirmed via <span class="co">[</span><span class="ot">`git show e0b1ea3:Procfile`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/e0b1ea3)</span>. The clean 15–19 minute runs from this period have nothing to do with combo2d. |</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>| Aug 13, 21:31 | <span class="co">[</span><span class="ot">`1a3b714`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/1a3b714)</span> | <span class="in">`combo2d_scheduler.py`</span> created; Procfile pointed at it for the first time |</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>| Aug 13, 23:58 | <span class="co">[</span><span class="ot">`cb070a5`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/cb070a5)</span> | Switched to <span class="in">`massive`</span>/<span class="in">`RESTClient`</span> for data — but <span class="in">`massive`</span> was never added to the root <span class="in">`requirements.txt`</span> |</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>| Aug 17, 14:45 | <span class="co">[</span><span class="ot">`321c747`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/321c747)</span> | "fix: add massive to scheduler requirements" — added <span class="in">`massive`</span> to <span class="in">`glitch/scheduler/requirements.txt`</span>, the **wrong file**: this service builds via Railpack, which reads the root <span class="in">`requirements.txt`</span>, not the scheduler subdirectory's copy. The fix had zero real effect. |</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>| Aug 17 – Aug 26 | — | **9 days with no commits** — the service failing silently, unnoticed |</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>| Aug 26–27 | <span class="co">[</span><span class="ot">`99497ec`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/99497ec)</span> | Security hardening merged (removed hardcoded Massive/Telegram fallbacks) — but <span class="in">`massive`</span> was still missing from the correct file, so execution still died *before* reaching the new Telegram check |</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>| Aug 28 | <span class="co">[</span><span class="ot">`44f07cf`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/44f07cf)</span> | Fixed the correct file (root <span class="in">`requirements.txt`</span>) — first time since Aug 13 the <span class="in">`massive`</span> import actually resolves |</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>| Aug 31 | — | With the import resolved, execution reached the *next* unmet requirement — the Telegram token — surfacing a new-looking error that was really the second domino in the same chain |</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>**Explicit conclusion:** this session's own security hardening (removing hardcoded fallbacks) was not the original cause — it stacked a second requirement (Telegram env vars) behind a pre-existing bug from 17 August that touched the wrong file. Any COMBO2D "Win Rate" or "PnL Total" Telegram report between 14 August and the fix must be treated as **nonexistent, not as contaminated data** — the service simply never ran.</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>**Related, separate bug found earlier in the same investigation** — an intermediate commit (<span class="co">[</span><span class="ot">`4eed7ca`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/4eed7ca)</span>) found that the Nixpacks build phase (a different build path than the Railpack one actually in use) installs from <span class="in">`glitch/scheduler/requirements.txt`</span>, not the root file — the opposite convention from Railpack. Two build systems reading two different requirements files was the structural reason the same class of bug ("added the dependency, to the wrong file") could recur.</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="fu">## Deployment configuration inconsistency — four files, three different start commands</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>While preparing to add a second Railway service (for the Cerebro 1 geometry candidate), an audit found four config files disagreeing on the start command:</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>| File | Start command |</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>| <span class="in">`nixpacks.toml`</span> (root) | <span class="in">`python glitch/scheduler/glitch_scheduler.py`</span> |</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>| <span class="in">`Procfile`</span> (root) | <span class="in">`python glitch/scheduler/combo2d_scheduler.py`</span> |</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>| <span class="in">`glitch/Procfile`</span> | <span class="in">`python scheduler/glitch_scheduler.py`</span> |</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>| <span class="in">`glitch/railway.json`</span> | <span class="in">`python scheduler/glitch_scheduler.py`</span> |</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>The initial hypothesis — that Railway's dashboard had a manual Start Command override ignoring these files — was checked directly and **ruled out**: the combo2d service's Start Command field is empty, meaning Railway genuinely reads one of the four files, yet 3 of 4 point to the old <span class="in">`glitch_scheduler.py`</span> while <span class="in">`combo2d_scheduler.py`</span> is confirmed to be what's actually running. This discrepancy was never fully resolved; it was treated as a live risk (never edit <span class="in">`nixpacks.toml`</span> or <span class="in">`glitch/Procfile`</span> without first confirming Railway's configured Root Directory) rather than guessed past. See <span class="co">[</span><span class="ot">`GLITCH_RESEARCH_LOG.md`, "Despliegue a Railway"</span><span class="co">](https://github.com/erictvillarreal/GLITCH/blob/99497ec/glitch/GLITCH_RESEARCH_LOG.md)</span>.</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ephemeral filesystem — ~~a data-quality problem~~ a total data-loss problem</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>Confirmed directly on Railway's dashboard: Cron Schedule-type services (GEOMETRY, and by the same service type, COMBO2D) have no Volumes option — **the filesystem resets between every cron execution.** Both schedulers stored their trade history in a local JSON file, so every run started from a blank slate. Every "Día X de paper" or "pass_rate acumulado" message ever sent to Telegram before this fix reflected, at most, a single day's cycle — never a real accumulation, even though the message read like a running total. Once the COMBO2D crash chain above was reconstructed, this was revealed to be moot for that period specifically (there was no successful run to lose state from until 28 August), but it remained a live, general risk for GEOMETRY.</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>**Fix:** <span class="co">[</span><span class="ot">`6a548a3`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/6a548a3)</span> — <span class="in">`execution/gist_store.py`</span>, a private GitHub Gist accessed via the REST API, as the single persistence backend for both schedulers, replacing local-file I/O behind the same <span class="in">`load_log()`</span>/<span class="in">`save_log()`</span> interface. Two alternatives were evaluated and rejected first: Railway Volumes (confirmed unavailable for this service type) and reading the bot's own message history back via Telegram's <span class="in">`getUpdates`</span> (confirmed technically impossible — the Bot API never returns a bot's own sent messages to itself). Failure philosophy is deliberately asymmetric: missing configuration (<span class="in">`GITHUB_GIST_TOKEN`</span>, <span class="in">`GIST_ID`</span>) raises immediately rather than silently starting a scheduler that thinks it's on day one; a transient network failure during a well-configured run logs but does not crash the scheduler, since the day's trade has already executed and been notified by that point. 10 dedicated tests (<span class="in">`tests/test_gist_store.py`</span>, no real network — mocked <span class="in">`requests.get`</span>/<span class="in">`requests.patch`</span>) plus integration coverage in both parity test files; full suite 110/110.</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="fu">## Unified startup environment check</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>The COMBO2D crash chain's real underlying pattern — five separate root causes discovered one crash at a time, each hiding the next — prompted a structural fix rather than another one-off patch: <span class="co">[</span><span class="ot">`a24400f`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/a24400f)</span> added <span class="in">`execution/env_check.py`</span>, called as the very first line of both schedulers, before any of the three modules (<span class="in">`telegram_bot`</span>, <span class="in">`contracts`</span>, <span class="in">`gist_store`</span>) that each used to validate their own required variables independently, one crash-and-fix cycle apart. It checks all five required variables (<span class="in">`MASSIVE_API_KEY`</span>/<span class="in">`POLYGON_API_KEY`</span>, <span class="in">`TELEGRAM_BOT_TOKEN`</span>, <span class="in">`TELEGRAM_CHAT_ID`</span>, <span class="in">`GITHUB_GIST_TOKEN`</span>, <span class="in">`GIST_ID`</span>) at once and sends a single Telegram message listing every missing one, rather than surfacing them serially across separate days. Verified with 6 unit tests plus a real build-environment smoke test: importing each scheduler under <span class="in">`env -i`</span> with exactly the 7 variables Railway has configured, confirming a clean import end-to-end, not just a passing check. A manual "Run now" trigger on 2 September 2026 gave the first real, clean end-to-end log for COMBO2D since the incident began — full suite 118/118 passing at that point.</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>::: {.callout-important}</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>Fixing the crash chain is infrastructure hygiene, not evidence of trading edge. COMBO2D is technically healthy today (it runs start to finish without error) — but it remains the <span class="in">`combo_2d`</span> mean-reversion candidate already discarded on statistical grounds (fresh reproduction gave p≈0.44–0.45; see <span class="co">[</span><span class="ot">Cerebro 1 Timeline</span><span class="co">](01-cerebro1-timeline.qmd)</span> and <span class="co">[</span><span class="ot">Methodology &amp; Discipline</span><span class="co">](04-metodologia-y-disciplina.qmd)</span>). A clean log is not a signal.</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="fu">## Yahoo Finance MES=F opening-window delay</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>An earlier, separate incident chain (predating the Massive migration) affected the ORB-based scheduler's live entry: Yahoo Finance's free MES=F feed frequently had no data yet at the scheduled 9:30 CT entry check, producing zero-range opening bars. Fixed iteratively across several commits — skip the trading day if the scheduler starts after the ORB window closes (<span class="co">[</span><span class="ot">`e038911`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/e038911)</span>), retry on a zero-range ORB instead of assuming the market itself was flat (<span class="co">[</span><span class="ot">`53b03a6`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/53b03a6)</span>), correct the retry's sleep target (<span class="co">[</span><span class="ot">`ada0bc0`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/ada0bc0)</span>), log actual bar timestamps to confirm the fetch window truly aligned with 9:30–9:34 (<span class="co">[</span><span class="ot">`1a8a76c`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/1a8a76c)</span>), widen the entry-fetch window with per-attempt diagnostics (<span class="co">[</span><span class="ot">`7e0d53d`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/7e0d53d)</span>) — and finally diagnosed with a dedicated standalone real-time probe deployed as its own one-shot Railway service (<span class="co">[</span><span class="ot">`97c522a`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/97c522a)</span>, <span class="co">[</span><span class="ot">`73a4ab9`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/73a4ab9)</span>) rather than guessed at from inside the live scheduler. This data-reliability problem, among others, motivated the later migration to Massive as the primary market-data source.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## Massive migration — API pagination quirk found twice</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>Massive's REST API has a specific, non-obvious failure mode: requesting a date range with <span class="in">`sort=window_start.asc`</span> and taking the last row of the response does **not** reliably return the most recent bar — confirmed independently on two different endpoints, seven days apart:</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>**First occurrence — `/futures/v1/contracts`** (during the original Massive migration): a point-in-time <span class="in">`date=`</span> query works reliably; a wide date range with ascending sort does not.</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>**Second occurrence — `/futures/v1/aggs/{ticker}`, MGC delay probe (07 September 2026):** a first attempt to measure Massive's real-time data delay for MGC (`scripts/probe_massive_mgc_delay.py`) returned an impossible result — **~319,174 minutes (over 7 months) of "delay."** Rather than re-run the measurement blindly, three query variants were tested side by side against the same endpoint (<span class="in">`scripts/diagnose_massive_aggs_query.py`</span>, <span class="co">[</span><span class="ot">commit `e56322e`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/e56322e)</span>):</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**A)** Date-only range bounds + <span class="in">`sort=window_start.asc`</span> + high <span class="in">`limit`</span>, taking the last result (the pattern that worked for full historical downloads in <span class="in">`fetch_mes_2y.py`</span>)</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**B)** Same pattern with full datetime + timezone offset instead of a bare date</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**C)** No date range at all — <span class="in">`sort=window_start.desc`</span> + <span class="in">`limit=1`</span>, asking directly for "the most recent bar you have"</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>**Only C works.** A and B both fail identically regardless of date-format — confirming this is an API pagination/ordering issue specific to `sort=asc` + range + take-last, the same failure class already seen on `/futures/v1/contracts`, not a one-off. **Rule adopted for any future "give me the latest" query against Massive: `sort=desc` + small `limit`, never a date range with `sort=asc` and take-the-last-element.** Fixed in <span class="co">[</span><span class="ot">commit `2a1c910`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/2a1c910)</span>.</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>A second, independent measurement artifact was caught in the same fix: the corrected probe's first real run measured ~1.8 days of "delay" — but it ran on a **Saturday**, so the number was elapsed time since Friday's market close (gold trades Fri 16:00 CT–Sun 17:00 CT), not real API latency. A <span class="in">`_weekday_warning()`</span> guard was added so the probe flags itself when run outside active weekday market hours; the real delay measurement remains pending a weekday run.</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="fu">## MGC's real trading-liquidity window was miscalibrated — for the whole dataset, not just live entry</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>While building the third scheduler's entry-window logic (Cerebro 2's checklist item explicitly warning not to assume equity-index RTH conventions transfer to other products), a deeper problem surfaced: the *entire* <span class="in">`mgc_5min_2y.parquet`</span> dataset already used to validate this candidate's win rate had the same miscalibration. <span class="in">`fetch_mes_2y.py`</span> (reused to fetch MGC) filtered to "8:30–15:00 CT, standard for index products" — a filter written for equity index and never revisited for gold.</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>Checked against two independent external sources — CME/COMEX's legacy pit session (7:20–12:30 CT) and the commonly cited London-NY overlap window for gold's highest real liquidity (7:00–11:00 CT) — both place gold's real active window **1–1.5 hours earlier** than 8:30 CT. Internal evidence corroborated this independently: in the existing dataset, the very first captured bar (8:30 CT) was already the day's volume peak (29.1% of the day's total volume in that first hour alone), decaying monotonically afterward — a slope that, extrapolated backward, suggests the untouched 7:00–8:30 CT window was probably *more* active than anything already captured, not less. <span class="co">[</span><span class="ot">Commit `47350ba`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/47350ba)</span>.</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>A corrected-window fetch script (<span class="in">`scripts/fetch_mgc_correct_window.py`</span>) was prepared but not run locally (blocked on <span class="in">`MASSIVE_API_KEY`</span>, deliberately not passed into this session per the project's key-handling rule) — the user ran it from their own environment. Comparison, once the corrected dataset (49,395 bars, 7:00–15:00 CT, +22.9% more data) came back:</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>| | Old window (8:30–15:00 CT) | **Corrected window (7:00–15:00 CT)** |</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>| Conditional WR (all) | 49.97% | **50.20%** |</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>| WR long / short | 52.78% / 47.16% (5.62pp gap) | **50.47% / 49.93%** (0.54pp gap) |</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>| Combine pass rate (alternating) | 47.0% | **47.5%** |</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>The corrected window is now the reference dataset for this candidate: it captured meaningfully more data, pushed the win rate even closer to the 50% theoretical assumption, and **nearly eliminated the long/short asymmetry** — consistent with the idea that part of that asymmetry was an artifact of excluding the window where buy/sell order flow is most balanced, not a genuine market bias. The Combine pass rate barely moved (47.0% → 47.5%), so the central conclusion that this candidate is weak for the Combine phase (vs. G2's 81.4%) is unaffected. <span class="co">[</span><span class="ot">Commit `0ef0c15`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/0ef0c15)</span> confirms this was a real improvement, not just a formality. A stale-hardcoded-aggregate bug caught in the comparison script itself along the way (<span class="co">[</span><span class="ot">commit `3f0bd07`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/3f0bd07)</span>) is documented in <span class="co">[</span><span class="ot">Cerebro 2 Timeline</span><span class="co">](02-cerebro2-timeline.qmd)</span>.</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>This finding is scoped to MGC specifically — <span class="in">`mgc_5min_2y.parquet`</span> (old window) remains valid and untouched for the original, narrower-barrier <span class="in">`CANDIDATES["MGC"]`</span> geometry used in Cerebro 1's product grid, which is not affected by the same time-exit dynamics.</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="fu">## Same-day finding: UTC-mislabeled-as-CT logger (07 September 2026)</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>Found while writing this report, not during the original edge search: all 3 production schedulers (<span class="in">`geometry_scheduler.py`</span>, <span class="in">`combo2d_scheduler.py`</span>, <span class="in">`glitch_scheduler.py`</span>) used <span class="in">`logging.basicConfig(format="%(asctime)s CT ...")`</span> — a literal <span class="in">`"CT"`</span> string in the format, with <span class="in">`%(asctime)s`</span> defaulting to <span class="in">`time.localtime()`</span>. This showed the correct time **only because** Railway happens to have <span class="in">`TZ=America/Chicago`</span> set; had that variable ever been absent (the typical default for a bare Docker container is UTC), every log line would have shown UTC time mislabeled as CT, with no visible error. Confirmed empirically (forcing <span class="in">`TZ=UTC`</span> vs. <span class="in">`TZ=America/Chicago`</span> before applying any fix) rather than assumed already-fixed from a passing description.</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>**Fix:** a new single-source-of-truth module, <span class="co">[</span><span class="ot">`execution/ct_logging.py`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/blob/484187c/glitch/execution/ct_logging.py)</span>, with a <span class="in">`CTFormatter`</span> whose <span class="in">`converter`</span> explicitly resolves to <span class="in">`zoneinfo.ZoneInfo("America/Chicago")`</span>, independent of the process's <span class="in">`TZ`</span> or <span class="in">`time.localtime()`</span>. A permanent regression test (<span class="in">`tests/test_ct_logging.py`</span>) forces <span class="in">`TZ=UTC`</span> at the process level and confirms logged timestamps still reflect real Chicago time, including a summer case to confirm DST is honored rather than a fixed offset. Applied in <span class="co">[</span><span class="ot">commit `484187c`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/484187c)</span> (<span class="in">`main`</span>: <span class="in">`geometry_scheduler.py`</span>, <span class="in">`combo2d_scheduler.py`</span>, <span class="in">`glitch_scheduler.py`</span>) and <span class="co">[</span><span class="ot">commit `0be4b01`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/commit/0be4b01)</span> (<span class="in">`cerebro2-dev`</span>: <span class="in">`geometry_mgc_scheduler.py`</span>).</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>**Side finding, unrelated to the fix itself:** smoke-testing `glitch_scheduler.py` revealed it **cannot be imported at all** — `from scheduler.telegram_bot import notify_signal, notify_exit, ...` fails, because those functions no longer exist in `telegram_bot.py` (replaced at some point by the Brain1/Brain2 template rework; current exports are `send`, `notify_brain1_open/close/no_signal`, `notify_brain2_open/close/no_signal`, and related functions). Confirmed via `git diff` to be pre-existing, unrelated to this logging fix. This is strong circumstantial evidence that `glitch_scheduler.py` is orphaned code — if it were the service actually running behind the root `Procfile`'s `worker:` line, it would be visibly crash-looping since the Brain1/Brain2 rework, which is unlikely to have gone unnoticed for this long. **Not fixed** — out of scope for this same-day finding; deployment dashboards for GEOMETRY, GEOMETRY-MGC, and GLITCH all confirmed "Deployment successful" as of this writing (06 September 2026, a Sunday with no active cron), but which specific file the Railway service named "GLITCH" actually executes was not conclusively confirmed in this session.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>**Correction to the bug list for this report:** of the 4 items originally slated to appear as "bugs found during the edge search," only 2 have a confirmed root cause and fix from that original search: the <span class="in">`triple_barrier.py`</span> ambiguous-bar bug and the ZC tick-size unit mismatch (both in <span class="co">[</span><span class="ot">Cerebro 1 Timeline</span><span class="co">](01-cerebro1-timeline.qmd)</span>). "MES/MNQ tick value confusion" is dropped — no evidence it was ever a real bug. The UTC-as-CT logger bug documented here is a same-day finding from writing this report, not a historical artifact of the original edge search — the two timelines are kept separate deliberately, not conflated.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/erictvillarreal/GLITCH/edit/main/03-infraestructura-operaciones.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/erictvillarreal/GLITCH/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>