<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eric Trevino">
<meta name="dcterms.date" content="2026-09-06">

<title>GLITCH</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./01-cerebro1-timeline.html" rel="next">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-0626ff4d7a71b55c8707dcae1d04a9b6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5286facc3d161db56da1629c96e68e53.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">GLITCH</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <a href="https://github.com/erictvillarreal/GLITCH" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./index.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Executive Summary</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Executive Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-cerebro1-timeline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Cerebro 1 — Timeline</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-cerebro2-timeline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Cerebro 2 — Timeline</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-infraestructura-operaciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Infrastructure &amp; Operations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-metodologia-y-disciplina.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Methodology &amp; Discipline</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-glosario.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Glossary</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary"><span class="header-section-number">1</span> Executive Summary</a>
  <ul class="collapse">
  <li><a href="#what-is-glitch" id="toc-what-is-glitch" class="nav-link" data-scroll-target="#what-is-glitch"><span class="header-section-number">1.1</span> What is GLITCH</a></li>
  <li><a href="#current-status" id="toc-current-status" class="nav-link" data-scroll-target="#current-status"><span class="header-section-number">1.2</span> Current Status</a></li>
  <li><a href="#snapshot-cerebro-1-g2-candidate" id="toc-snapshot-cerebro-1-g2-candidate" class="nav-link" data-scroll-target="#snapshot-cerebro-1-g2-candidate"><span class="header-section-number">1.3</span> Snapshot — Cerebro 1 (G2 candidate)</a></li>
  <li><a href="#snapshot-cerebro-2-mgc150k-geometry-pure-candidate" id="toc-snapshot-cerebro-2-mgc150k-geometry-pure-candidate" class="nav-link" data-scroll-target="#snapshot-cerebro-2-mgc150k-geometry-pure-candidate"><span class="header-section-number">1.4</span> Snapshot — Cerebro 2 (MGC/150K geometry-pure candidate)</a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings"><span class="header-section-number">1.5</span> Key Findings</a></li>
  <li><a href="#how-to-read-this-report" id="toc-how-to-read-this-report" class="nav-link" data-scroll-target="#how-to-read-this-report"><span class="header-section-number">1.6</span> How to Read This Report</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/erictvillarreal/GLITCH/edit/main/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/erictvillarreal/GLITCH/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">GLITCH</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">Multi-Strategy Futures Prop-Firm Research Report</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eric Trevino </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 6, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="executive-summary" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Executive Summary</h1>
<section id="what-is-glitch" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="what-is-glitch"><span class="header-section-number">1.1</span> What is GLITCH</h2>
<p>GLITCH is a research program to systematically pass a Topstep futures prop-firm evaluation (the “Combine”) and then generate real payouts from the resulting funded account (the “XFA”). The project runs two parallel, independently-optimized tracks referred to throughout this report as <strong>Cerebro 1</strong> and <strong>Cerebro 2</strong>.</p>
<p><strong>Cerebro 1 — pass the Combine.</strong> Objective: maximize the probability of reaching the profit target within a bounded ~15-day evaluation window, where the maximum loss is capped at the fee of the attempt (~$49–149). This bounded-loss, bounded-time structure permits a strategy to pass reliably even without genuine predictive edge — convexity of the payout does the work, not market prediction.</p>
<p><strong>Cerebro 2 — survive and generate payouts once funded.</strong> A fundamentally different problem: the horizon is unbounded, there is no profit target, and the relevant threshold is 5 winning days of ≥$150 net, not a lump-sum target. A strategy with zero or negative net edge that reliably passes the Combine does <strong>not</strong> survive Cerebro 2 — without the bounded window protecting it, the trailing loss limit (MLL) eventually catches any strategy without genuine positive edge.</p>
</section>
<section id="current-status" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="current-status"><span class="header-section-number">1.2</span> Current Status</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Track</th>
<th>Status</th>
<th>Key number</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Cerebro 1</strong></td>
<td>Validated candidate (“G2”) live in real paper trading on Railway</td>
<td>~70.6% empirical win rate (MES, SL=100/TP=40 ticks), 81.44% theoretical Combine pass rate</td>
<td><a href="https://github.com/erictvillarreal/GLITCH/blob/99497ec/glitch/GLITCH_RESEARCH_LOG.md"><code>GLITCH_RESEARCH_LOG.md</code>, “Consolidación — Camino B”</a></td>
</tr>
<tr class="even">
<td><strong>Cerebro 2</strong></td>
<td>Geometry-pure candidate (MGC/150K) validated on both of its core assumptions; real-edge search (712 tests) found no candidate meeting the N&gt;200 bar; a structural finding shows the Combine and XFA phases need <em>opposite</em> geometries</td>
<td>Empirical WR 50.20% (vs.&nbsp;50% theoretical); Combine pass rate for this same candidate: only 47.5% (vs.&nbsp;G2’s 81.4%)</td>
<td><a href="https://github.com/erictvillarreal/GLITCH/blob/0be4b01/glitch/GLITCH_RESEARCH_LOG.md"><code>GLITCH_RESEARCH_LOG.md</code>, “HALLAZGO ESTRUCTURAL CENTRAL DE CEREBRO 2”</a></td>
</tr>
</tbody>
</table>
<p><strong>Capital deployment decision date: 27 September 2026</strong> (per project governance document).</p>
</section>
<section id="snapshot-cerebro-1-g2-candidate" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="snapshot-cerebro-1-g2-candidate"><span class="header-section-number">1.3</span> Snapshot — Cerebro 1 (G2 candidate)</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Product / geometry</td>
<td>MES, SL=100/TP=40 ticks (RR=0.40), alternating direction, nc=40</td>
<td><a href="https://github.com/erictvillarreal/GLITCH/blob/99497ec/glitch/strategies/geometry_pure.py"><code>strategies/geometry_pure.py</code></a></td>
</tr>
<tr class="even">
<td>Empirical win rate</td>
<td>~70.6% (midpoint of optimistic/conservative bracket, post ambiguous-bar fix)</td>
<td><code>scripts/revalidate_geometry_table.py</code></td>
</tr>
<tr class="odd">
<td>Theoretical Combine pass rate</td>
<td>81.44% (<code>THEORETICAL_PASS_RATE</code>, Monte Carlo, n_paths=8,000, seed=42)</td>
<td><a href="https://github.com/erictvillarreal/GLITCH/blob/484187c/glitch/scheduler/geometry_scheduler.py"><code>scheduler/geometry_scheduler.py</code></a></td>
</tr>
<tr class="even">
<td>Estimated combines/year</td>
<td>53.6</td>
<td><code>scripts/camino_b_grid.py</code> results</td>
</tr>
<tr class="odd">
<td>Operational status</td>
<td>Live paper trading on Railway (“GEOMETRY” service)</td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
<section id="snapshot-cerebro-2-mgc150k-geometry-pure-candidate" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="snapshot-cerebro-2-mgc150k-geometry-pure-candidate"><span class="header-section-number">1.4</span> Snapshot — Cerebro 2 (MGC/150K geometry-pure candidate)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geometry</td>
<td>MGC, SL=TP=364 ticks (RR=1.0), alternating, nc=6</td>
<td><code>strategies/geometry_pure.py::CANDIDATES["MGC_XFA_150K"]</code> (cerebro2-dev)</td>
</tr>
<tr class="even">
<td>Empirical WR (corrected liquidity window)</td>
<td>50.20%, stable across 3 independent sub-periods (49.90–50.13%)</td>
<td><code>scripts/validate_mgc_wr_empirical.py</code></td>
</tr>
<tr class="odd">
<td><strong>Combine pass rate for this same geometry</strong></td>
<td><strong>47.5%</strong> — far below G2’s 81.4%</td>
<td><code>scripts/cerebro2_cashflow_monte_carlo.py</code></td>
</tr>
<tr class="even">
<td>1-year chained cash-flow (median, p10–p90)</td>
<td>$31,257 ($15,809–$53,861)</td>
<td>Same script</td>
</tr>
<tr class="odd">
<td>Capital cushion needed (median / p90)</td>
<td>$894 / $2,679</td>
<td>Same script</td>
</tr>
<tr class="even">
<td>Real-edge search coverage</td>
<td>712 statistical tests across products, pairs, hold periods; best candidate p=0.0003 but N=128 (&lt; the 200 minimum)</td>
<td><code>GLITCH_RESEARCH_LOG.md</code>, edge-search sections</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Numbers that were retracted or never reproduced — stated explicitly, not omitted.</strong> A <strong>$134,174</strong> payout figure appeared in an earlier Cerebro 2 analysis and was later confirmed to be <strong>fabricated</strong> by a prior AI session — it does not trace to any script in this repository and must never be used as a reference point. Two historical walk-forward candidates were cited with p-values of <strong>0.149</strong> and <strong>0.081</strong> — both looked like real edge, and <strong>neither ever reproduced</strong> when re-tested fresh in this repository (fresh reruns gave p≈0.44–0.45 for both). These two failures are the direct reason for the non-negotiable rigor standard in <a href="./04-metodologia-y-disciplina.html">Methodology &amp; Discipline</a>.</p>
</div>
</div>
</section>
<section id="key-findings" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="key-findings"><span class="header-section-number">1.5</span> Key Findings</h2>
<p><strong>Cerebro 1’s G2 candidate is real, reproducible, and does not depend on predictive signal.</strong> It exploits gambler’s-ruin geometry (SL/TP placement) within the Combine’s bounded-loss structure — validated against real MES price data with the triple-barrier ambiguous-bar bug fixed first (see <a href="./01-cerebro1-timeline.html">Cerebro 1 Timeline</a>).</p>
<p><strong>Cerebro 2’s central structural finding: optimizing for the Combine and optimizing for XFA survival are not the same problem, and can actively conflict.</strong> The MGC/150K candidate — designed to tolerate very few consecutive losses once funded — has a Combine pass rate of only 47.5%, roughly half of G2’s 81.4%, when run through the exact same, already-audited Combine simulator. No Cerebro 2 candidate’s Combine pass rate should ever be assumed from another candidate’s number (see <a href="./02-cerebro2-timeline.html">Cerebro 2 Timeline</a>).</p>
<p><strong>A vectorization bug turned a ~2-hour job into a projected ~70-hour one — caught before it ran unsupervised.</strong> An exhaustive Monte Carlo grid’s ETA climbed from an estimated 2 hours to a projected 70 hours after only 1% progress; the root cause was a scalar per-path Python loop whose cost varied ~75x across the parameter space. Vectorizing it (validated bit-exact against the old implementation across 32 cases before replacing it) cut the real run to 51 minutes (see <a href="./03-infraestructura-operaciones.html">Infrastructure &amp; Operations</a>).</p>
<p><strong>A live production incident chain cost ~2.5 weeks and traced to five distinct, unrelated root causes</strong> — a <code>requirements.txt</code> file read from the wrong path by the actual build system in use (Railpack, not the Nixpacks config that was being edited), missing Telegram/Massive environment variables discovered one crash at a time, an ephemeral filesystem silently resetting all persistence between cron runs, and a Yahoo Finance data-availability gap at the market open (see <a href="./03-infraestructura-operaciones.html">Infrastructure &amp; Operations</a>).</p>
<p><strong>A “10-minute” data delay claimed by a paid vendor was never verified — and a first attempt to verify it returned an impossible number, catching a second, unrelated API bug.</strong> A real-time delay probe for Massive’s futures data returned a 319,174-minute (7+ month) delay; the root cause was an unreliable API pagination pattern (<code>sort=asc</code> over a date range never returns the most recent record on this endpoint — confirmed with raw API evidence, not assumed) (see <a href="./03-infraestructura-operaciones.html">Infrastructure &amp; Operations</a>).</p>
</section>
<section id="how-to-read-this-report" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="how-to-read-this-report"><span class="header-section-number">1.6</span> How to Read This Report</h2>
<p>Every factual claim in this report links to a specific script, commit, or <code>GLITCH_RESEARCH_LOG.md</code> section in the <a href="https://github.com/erictvillarreal/GLITCH">GLITCH repository</a> — commit-hash-pinned where precision matters, so links stay valid even as branches move or get merged. This report is a navigable index into that history, not a replacement for it: <code>GLITCH_RESEARCH_LOG.md</code> (on the <code>main</code> and <code>cerebro2-dev</code> branches — the two have not yet been merged) remains the technical source of truth. Where a number was later invalidated, contradicted, or never reproduced, this report says so explicitly next to the number, not in a separate erratum.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
  </div>
  <div class="nav-page nav-page-next">
      <a href="./01-cerebro1-timeline.html" class="pagination-link" aria-label="Cerebro 1 — Timeline">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Cerebro 1 — Timeline</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Executive Summary</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## What is GLITCH</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>GLITCH is a research program to systematically pass a Topstep futures prop-firm evaluation (the "Combine") and then generate real payouts from the resulting funded account (the "XFA"). The project runs two parallel, independently-optimized tracks referred to throughout this report as **Cerebro 1** and **Cerebro 2**.</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>**Cerebro 1 — pass the Combine.** Objective: maximize the probability of reaching the profit target within a bounded ~15-day evaluation window, where the maximum loss is capped at the fee of the attempt (~$49–149). This bounded-loss, bounded-time structure permits a strategy to pass reliably even without genuine predictive edge — convexity of the payout does the work, not market prediction.</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>**Cerebro 2 — survive and generate payouts once funded.** A fundamentally different problem: the horizon is unbounded, there is no profit target, and the relevant threshold is 5 winning days of ≥$150 net, not a lump-sum target. A strategy with zero or negative net edge that reliably passes the Combine does **not** survive Cerebro 2 — without the bounded window protecting it, the trailing loss limit (MLL) eventually catches any strategy without genuine positive edge.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">## Current Status</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>| Track | Status | Key number | Source |</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>| **Cerebro 1** | Validated candidate ("G2") live in real paper trading on Railway | ~70.6% empirical win rate (MES, SL=100/TP=40 ticks), 81.44% theoretical Combine pass rate | <span class="co">[</span><span class="ot">`GLITCH_RESEARCH_LOG.md`, "Consolidación — Camino B"</span><span class="co">](https://github.com/erictvillarreal/GLITCH/blob/99497ec/glitch/GLITCH_RESEARCH_LOG.md)</span> |</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>| **Cerebro 2** | Geometry-pure candidate (MGC/150K) validated on both of its core assumptions; real-edge search (712 tests) found no candidate meeting the N&gt;200 bar; a structural finding shows the Combine and XFA phases need *opposite* geometries | Empirical WR 50.20% (vs. 50% theoretical); Combine pass rate for this same candidate: only 47.5% (vs. G2's 81.4%) | <span class="co">[</span><span class="ot">`GLITCH_RESEARCH_LOG.md`, "HALLAZGO ESTRUCTURAL CENTRAL DE CEREBRO 2"</span><span class="co">](https://github.com/erictvillarreal/GLITCH/blob/0be4b01/glitch/GLITCH_RESEARCH_LOG.md)</span> |</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>**Capital deployment decision date: 27 September 2026** (per project governance document).</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">## Snapshot — Cerebro 1 (G2 candidate)</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>| Metric | Value | Source |</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>| Product / geometry | MES, SL=100/TP=40 ticks (RR=0.40), alternating direction, nc=40 | <span class="co">[</span><span class="ot">`strategies/geometry_pure.py`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/blob/99497ec/glitch/strategies/geometry_pure.py)</span> |</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>| Empirical win rate | ~70.6% (midpoint of optimistic/conservative bracket, post ambiguous-bar fix) | <span class="in">`scripts/revalidate_geometry_table.py`</span> |</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>| Theoretical Combine pass rate | 81.44% (<span class="in">`THEORETICAL_PASS_RATE`</span>, Monte Carlo, n_paths=8,000, seed=42) | <span class="co">[</span><span class="ot">`scheduler/geometry_scheduler.py`</span><span class="co">](https://github.com/erictvillarreal/GLITCH/blob/484187c/glitch/scheduler/geometry_scheduler.py)</span> |</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>| Estimated combines/year | 53.6 | <span class="in">`scripts/camino_b_grid.py`</span> results |</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>| Operational status | Live paper trading on Railway ("GEOMETRY" service) | — |</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## Snapshot — Cerebro 2 (MGC/150K geometry-pure candidate)</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>| Metric | Value | Source |</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>| Geometry | MGC, SL=TP=364 ticks (RR=1.0), alternating, nc=6 | <span class="in">`strategies/geometry_pure.py::CANDIDATES["MGC_XFA_150K"]`</span> (cerebro2-dev) |</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>| Empirical WR (corrected liquidity window) | 50.20%, stable across 3 independent sub-periods (49.90–50.13%) | <span class="in">`scripts/validate_mgc_wr_empirical.py`</span> |</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>| **Combine pass rate for this same geometry** | **47.5%** — far below G2's 81.4% | <span class="in">`scripts/cerebro2_cashflow_monte_carlo.py`</span> |</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>| 1-year chained cash-flow (median, p10–p90) | $31,257 ($15,809–$53,861) | Same script |</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>| Capital cushion needed (median / p90) | $894 / $2,679 | Same script |</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>| Real-edge search coverage | 712 statistical tests across products, pairs, hold periods; best candidate p=0.0003 but N=128 (&lt; the 200 minimum) | <span class="in">`GLITCH_RESEARCH_LOG.md`</span>, edge-search sections |</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>::: {.callout-important}</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>**Numbers that were retracted or never reproduced — stated explicitly, not omitted.** A **$134,174** payout figure appeared in an earlier Cerebro 2 analysis and was later confirmed to be **fabricated** by a prior AI session — it does not trace to any script in this repository and must never be used as a reference point. Two historical walk-forward candidates were cited with p-values of **0.149** and **0.081** — both looked like real edge, and **neither ever reproduced** when re-tested fresh in this repository (fresh reruns gave p≈0.44–0.45 for both). These two failures are the direct reason for the non-negotiable rigor standard in <span class="co">[</span><span class="ot">Methodology &amp; Discipline</span><span class="co">](04-metodologia-y-disciplina.qmd)</span>.</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key Findings</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>**Cerebro 1's G2 candidate is real, reproducible, and does not depend on predictive signal.** It exploits gambler's-ruin geometry (SL/TP placement) within the Combine's bounded-loss structure — validated against real MES price data with the triple-barrier ambiguous-bar bug fixed first (see <span class="co">[</span><span class="ot">Cerebro 1 Timeline</span><span class="co">](01-cerebro1-timeline.qmd)</span>).</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>**Cerebro 2's central structural finding: optimizing for the Combine and optimizing for XFA survival are not the same problem, and can actively conflict.** The MGC/150K candidate — designed to tolerate very few consecutive losses once funded — has a Combine pass rate of only 47.5%, roughly half of G2's 81.4%, when run through the exact same, already-audited Combine simulator. No Cerebro 2 candidate's Combine pass rate should ever be assumed from another candidate's number (see <span class="co">[</span><span class="ot">Cerebro 2 Timeline</span><span class="co">](02-cerebro2-timeline.qmd)</span>).</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>**A vectorization bug turned a ~2-hour job into a projected ~70-hour one — caught before it ran unsupervised.** An exhaustive Monte Carlo grid's ETA climbed from an estimated 2 hours to a projected 70 hours after only 1% progress; the root cause was a scalar per-path Python loop whose cost varied ~75x across the parameter space. Vectorizing it (validated bit-exact against the old implementation across 32 cases before replacing it) cut the real run to 51 minutes (see <span class="co">[</span><span class="ot">Infrastructure &amp; Operations</span><span class="co">](03-infraestructura-operaciones.qmd)</span>).</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>**A live production incident chain cost ~2.5 weeks and traced to five distinct, unrelated root causes** — a <span class="in">`requirements.txt`</span> file read from the wrong path by the actual build system in use (Railpack, not the Nixpacks config that was being edited), missing Telegram/Massive environment variables discovered one crash at a time, an ephemeral filesystem silently resetting all persistence between cron runs, and a Yahoo Finance data-availability gap at the market open (see <span class="co">[</span><span class="ot">Infrastructure &amp; Operations</span><span class="co">](03-infraestructura-operaciones.qmd)</span>).</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>**A "10-minute" data delay claimed by a paid vendor was never verified — and a first attempt to verify it returned an impossible number, catching a second, unrelated API bug.** A real-time delay probe for Massive's futures data returned a 319,174-minute (7+ month) delay; the root cause was an unreliable API pagination pattern (<span class="in">`sort=asc`</span> over a date range never returns the most recent record on this endpoint — confirmed with raw API evidence, not assumed) (see <span class="co">[</span><span class="ot">Infrastructure &amp; Operations</span><span class="co">](03-infraestructura-operaciones.qmd)</span>).</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## How to Read This Report</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>Every factual claim in this report links to a specific script, commit, or <span class="in">`GLITCH_RESEARCH_LOG.md`</span> section in the <span class="co">[</span><span class="ot">GLITCH repository</span><span class="co">](https://github.com/erictvillarreal/GLITCH)</span> — commit-hash-pinned where precision matters, so links stay valid even as branches move or get merged. This report is a navigable index into that history, not a replacement for it: <span class="in">`GLITCH_RESEARCH_LOG.md`</span> (on the <span class="in">`main`</span> and <span class="in">`cerebro2-dev`</span> branches — the two have not yet been merged) remains the technical source of truth. Where a number was later invalidated, contradicted, or never reproduced, this report says so explicitly next to the number, not in a separate erratum.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/erictvillarreal/GLITCH/edit/main/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/erictvillarreal/GLITCH/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>